language: rust
cache:
  cargo: true
script:
  - cargo test --all
before_deploy:
  - cargo doc --no-deps --all
  - >-
    echo '<meta http-equiv=refresh content=0;url=prelude/index.html>' >
    target/doc/index.html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $TOKEN
  keep-history: true
  local-dir: target/doc
  on:
    branch: master
