language: rust
cache:
  cargo: true
install:
  - cargo install cargo-update; true
  - cargo install-update -i cargo-update
  - cargo install-update -i cargo-web
script:
  - cargo test --all
  - cargo web test -p prelude
  - cargo web test -p color
  - cargo web test -p geom
  - cargo web test -p rng
  - cargo web test -p timer
before_deploy:
  - cargo doc --no-deps --all
  - >-
    echo '<meta http-equiv=refresh content=0;url=prelude/index.html>' >
    target/doc/index.html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $TOKEN
  keep-history: true
  local-dir: target/doc
  on:
    branch: master
